# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19xWwv7BgSZBbUpIELuveiwrl6SsLd2Wk
"""

#Data Pre-processing Step  
# importing libraries  
import numpy as nm  
import pandas as pd  
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.impute import SimpleImputer

#from sklearn.ensemble import HistGradientBoostingRegressor

#importing datasets  
df= pd.read_csv('file (13).csv') 
df2 = df.drop(['Domain'],axis=1)
df2.dropna()


X = df2.drop('Label',axis=1)
y = df2['Label']
print(X.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size= 0.2, random_state=0) 
X.shape

from sklearn.impute import SimpleImputer
simputer = SimpleImputer(missing_values = nm.nan, strategy = 'mean')
simputer.fit(X_train)
X_train=simputer.transform(X_train)
X_test=simputer.transform(X_test)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)



from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train,y_train)

import pickle
pickle.dump(svclassifier,open('project.pkl','wb'))